#!/bin/bash

cd ~/HDD/workshop/archive/snippets

cp ~/HDD/workshop/autoMPG.ipynb autoMPG.ipynb
cp ~/HDD/workshop/MNIST.ipynb MNIST.ipynb

git add .
read -p "enter commit message "  > git commit -m 
# git commit -m 
git push origin master
